### ISSUE TITLE
Additional check for vertex and edge inheritance

### ISSUE THREAD

**Issue by protodef** [bitnine-oss/agens-graph#10]
Current implementation does not check whether `INHERITS` option has relations other than vertex and edge. Through #7, we are able to check `INHERITS` option.

And did we decide to allow multiple inheritance? If not, we have to restrict the number of parent vertices and edges to 1.

**Comment by kskim80** [comment]
We should check for vlabels or elabels to inherit proper vlabels or elabels.

And I think there's no reason to prohibit multiple inheritance. Is there any?

**Comment by gtyun** [comment]
This issue is processed in #30
