### ISSUE TITLE
Any binaries available?

### ISSUE THREAD

**Issue by johnberzy-bazinga** [bitnine-oss/agens-graph#111]
Hello,

Sorry if this is the wrong repository to post this, but I couldn't find any reference to a mailing list or chat.

I was wondering if there are any binaries available for Mac or Windows? 

I've tried to build from source on Mac OS X but it appears that the contrib extension[ pg_statinfo is not compatible with OS X](https://github.com/bitnine-oss/agens-graph/blob/master/contrib/pg_statsinfo/agent/common.h#L16).  

Thank you,
John

**Comment by protodef** [comment]
Thanks for the issue.

Currently, there is no prebuilt binary for Mac or Windows. But you can get it for Linux at [here](http://bitnine.net/downloads/).

We use `pg_statsinfo` to monitor AgensGraph, but it does not support Mac or Windows now. So, we've decided to temporarily disable it on all OS's except Linux (#112) until it becomes available on other OS's or we use different methods to monitor AgensGraph.

Now, you can build the binary from the source on Mac OS X.

Thank you.

**Comment by johnberzy-bazinga** [comment]
Thanks a lot for the quick fix!
