### ISSUE TITLE
Config script errors on Ubuntu

### ISSUE THREAD

**Issue by dmikov** [bitnine-oss/agens-graph#114]
Running ag-config.sh script as indicated in readme produces following errors.
```
dmikov@dmikov-Virtual-Machine:~/Documents/agens-graph-master$ ./ag-config.sh
./ag-config.sh: 29: ./ag-config.sh: Syntax error: "(" unexpected (expecting ";;")
```
after removing case statement, it produces more errors

```
dmikov@dmikov-Virtual-Machine:~/Documents/agens-graph-master$ ./ag-config.sh
./ag-config.sh: 34: ./ag-config.sh: Bad substitution
```

**Comment by protodef** [comment]
What is the shell and the version of it you use?
I've tested the script on GNU bash 4.3.42 and it currently works.

**Comment by dmikov** [comment]
postgres@dmikov-Virtual-Machine:~$ bash --version
GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by johnberzy-bazinga** [comment]
I also had the same issue on Ubuntu. As a workaround I just called ./configure directly with the parameters copied from ag-config.sh.

**Comment by taewhi** [comment]
In my case, it works after I changed 'sh' to 'bash' in the first line.

**Comment by dmikov** [comment]
@johnberzy-bazinga I tried, but I am getting this at the end
`configure: error: could not find function 'gss_init_sec_context' required for GSSAPI`

**Comment by dmikov** [comment]
@taewhi Yes that made it work for me too, still have and error I indicated above :(

**Comment by johnberzy-bazinga** [comment]
@dmikov @taewhi 

I'm having issues building on ubuntu as well. For the error `configure: error: could not find function 'gss_init_sec_context' required for GSSAPI` I found i needed to install an extra dependency : `libkrb5-dev` . @protodef do you know if this is this the right dep? 

The other issue is contrib/pg_hint_plan is missing an `ifdef USE_PGXS` at https://github.com/bitnine-oss/agens-graph/blob/master/contrib/pg_hint_plan/Makefile#L21.

This is the error I'm seeing. Maybe I also need additional changes pg_hint_plan?

make[2]: pg_config: Command not found
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/home/parallels/Work/agens-graph/contrib/pg_hint_plan'
Makefile:96: recipe for target 'all-pg_hint_plan-recurse' failed
make[1]: *** [all-pg_hint_plan-recurse] Error 2

Thanks,
John

**Comment by kskim80** [comment]
@johnberzy-bazinga You don't need libraries like GSSAPI unless you need the authentication method. So just use ``./configure`` not ``ag-config.sh``, which is for making a distribution package in fact. I updated the install method of README.md. 

And for ``pg_hint_plan``, it needs ``pg_config`` executable to be made before compiling it. So first run ``make install`` and then ``make install-world``.

Thanks
Kisung Kim.

**Comment by johnberzy-bazinga** [comment]
@kskim80 Thanks for the reply. Your suggestion fixed my first issue regarding pg_config, however, now the build is complaining that it can't find pgxs.mk. It appears to be looking in `/agens-graph/lib/pgxs/src/makefiles/pgxs.mk` but for me the path to pgxs.mk resides in `/agens-graph/lib/postgresql/pgxs/src/makefiles/pgxs.mk` i.e. there is an additional folder named postgresql under lib.

Output:

`make -C pg_hint_plan install
make[2]: Entering directory '/home/parallels/Work/agens-graph/contrib/pg_hint_plan'
Makefile:23: /home/parallels/Work/agens-graph/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make[2]: *** No rule to make target '/home/parallels/Work/agens-graph/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.
make[2]: Leaving directory '/home/parallels/Work/agens-graph/contrib/pg_hint_plan'
Makefile:96: recipe for target 'install-pg_hint_plan-recurse' failed
make[1]: *** [install-pg_hint_plan-recurse] Error 2
make[1]: Leaving directory '/home/parallels/Work/agens-graph/contrib'
GNUmakefile:35: recipe for target 'install-world-contrib-recurse' failed
make: *** [install-world-contrib-recurse] Error 2
`

Thanks for the help,
John

**Comment by kskim80** [comment]
@johnberzy-bazinga It is right that ``pgxs.mk`` resides in ``/agens-graph/lib/postgresql/pgxs/src/makefiles/pgxs.mk``. But the build script seems to find the file in wrong place. I think you try to clean all things and build AgensGraph as follows;

```bash
make distclean
./configure --prefix=`pwd`
make install
export PATH=`pwd`/bin:$PATH
make install-world
```
If you have any problem, please let us know.

Thank you.
Kisung.

**Comment by johnberzy-bazinga** [comment]
@kskim80 that worked like a charm. Thanks for the help.

**Comment by kskim80** [comment]
@johnberzy-bazinga Thank you for your feedback.
