### ISSUE TITLE
Support for binary in/out for graph types

### ISSUE THREAD

**Issue by johnberzy-bazinga** [bitnine-oss/agens-graph#115]
Hello,

I've come across an issue while testing some queries with agens-graph using the .NET [(NpgSql)](https://github.com/npgsql/npgsql) client.

Given the following query `MATCH (v) RETURN v;` the server returns an exception due to the client defaulting to the binary protocol. AFAICT the various graph types do not implement the required in/out methods for binary encoding.

There are a couple of workarounds such as forcing a cast on the relevant types `MATCH (v) RETURN v::text` or forcing the text-based encoding entirely or on a per-column basis. This is less than ideal however, since it requires that the user/library have pre-execution knowledge of the relevant column types or completely switch to the text-based protocol.

If binary support is added, I'd be more than happy to fork and add support for the graph types on the NpgSql side.

Thank you,
John

**Comment by mlogue** [comment]
Thank you for your interest in agens-graph.
We do not support the binary protocol and .NET.
It will be supported in the near future.

**Comment by johnberzy-bazinga** [comment]
@mlogue Fantastic! Great job on this project. I've been looking for a solution like this for a long time.

**Comment by kskim80** [comment]
@johnberzy-bazinga Thank you for you interests and contribution!. We will review your code and decide to merge it.

**Comment by johnberzy-bazinga** [comment]
@kskim80 Thanks! Let me know if you'd like to see any changes made to the PR. This would really be helpful on the (Npgsql/.NET) side of things. Vertex, Edge, and Graphpath seem to be handled fine with the binary record handler, but graphid is the exception.

Thanks!
John

**Comment by pratikpparikh** [comment]
@johnberzy-bazinga, @kskim80  did you PR ever got accepted?  I am facing the same problem with binary support?
