### ISSUE TITLE
[Bug] Duplicate key violations when creating property indexes concurrently

### ISSUE THREAD

**Issue by kskim80** [bitnine-oss/agens-graph#142]
CREATE PROPERTY INDEX failed due to the following error:

```
ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(Comment_property_idx, 96465) already exists.
```

It can be reproduced by issuing several CREATE PROPERTY INDEX DDLs on one vertex label.
It might be due to the race condition in determining property index names.

**Comment by protodef** [comment]
This problem only occurs when multiple property indices on the same label are being created concurrently without explicit name of the index in each session. There is the same problem when creating normal indices. To reduce such naming conflics, I merged #143 which generates more appropriate name for such indices based on index parameters. Currently, there is no suitable solution of the problem although the pull request resolves some cases of it.
